### ISSUE TITLE
jtopl.f missing

### ISSUE THREAD

**Issue by bit-hack** [jotego/jtopl#8]
First of all thanks for making this project and releasing it, is really great.

When playing around with the verilator vgm player, I noticed that the `jtopl.f` file is missing from the hdl directory.
Both `gather.f` and `jtlopl2.f` still refer to this file.

I was able to get things running again by checking out the `jtopl.f` file from a previous commit.

It seems like commit 8d02416ae0ce8343e2823fcbe7ed072e2b523be0 removed this file.

I assume this was by mistake as it was added explicitly in commit a38aeac5ab5f9ea9021246ab2dac7b23599438dc.

**Comment by jotego** [comment]
I am deprecating the use of separate .f and .qip files in favour of a single .yaml file, which is parsed by [jtfiles](https://github.com/jotego/jtframe/blob/master/bin/jtfiles.go).

The transition is not finished in some repositories, like in this one, the simulation script should try to run jtfiles.go to extract the .f file from the .yaml. 

I should actually delete the other .f files too. I'll get to it.

**Comment by jotego** [comment]
The simulation script calls jtfiles.go to generate the .f files in commit 6797ed2
This will get merge in the main branch once OP-LL support is done.
